version: '2.2'

services:
  mediawiki:
    build:
        context: .
        dockerfile: Dockerfile
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    ports:
      - "8001:80"
    networks:
      default:
        aliases:
         - mediawiki.svc
    environment:

      - WBSTACK_LOAD_MW_INTERNAL=yes # THIS is normally hidden
      - PLATFORM_API_BACKEND_HOST=api.svc

      - MW_DB_SERVER_MASTER=mysql.svc:3306
      - MW_DB_SERVER_REPLICA=mysql-replica.svc:3306

      - MW_REDIS_SERVER_READ=redis.svc
      - MW_REDIS_SERVER_WRITE=redis.svc
      - MW_REDIS_PASSWORD=

    volumes:
      - ".:/var/www/html/w:cached"
      - ./wbstack/data/php.ini:/usr/local/etc/php/php.ini

  api:
    build:
      context: wbstack/test/
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
         - api.svc
    ports:
      - "8002:80"
    volumes:
      - ./wbstack/test/server.php:/var/www/html/index.php
      - ./wbstack/data/:/var/www/data/
      - ./wbstack/data/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    depends_on:
      - mysql-configure-replication
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
      - ./wbstack/docker-compose/mysql/main:/mwdd-custom
      - ./wbstack/data/mw1.35-wbs1.sql:/docker-entrypoint-initdb.d/mw1.35-wbs1.sql
    entrypoint: "/mwdd-custom/entrypoint.sh"
    command: "mysqld"
    environment:
      MYSQL_DATABASE: 'mwdb_somedb'
      MYSQL_USER: 'mwu_someuser'
      MYSQL_PASSWORD: 'somepassword'
      MYSQL_ROOT_PASSWORD: 'toor'
    networks:
      default:
        aliases:
         - mysql
         - mysql.svc

  mysql-replica:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: 'mwdb_somedb'
      MYSQL_USER: 'mwu_someuser'
      MYSQL_PASSWORD: 'somepassword'
      MYSQL_ROOT_PASSWORD: 'toor'
    depends_on:
      - mysql
      - mysql-replica-configure-replication
    volumes:
      - mysql-replica-data:/var/lib/mysql
      - ./wbstack/docker-compose/mysql/replica:/mwdd-custom
      - ./wbstack/data/mw1.35-wbs1.sql:/docker-entrypoint-initdb.d/mw1.35-wbs1.sql
    entrypoint: "/mwdd-custom/entrypoint.sh"
    command: "mysqld"
    networks:
      default:
        aliases:
         - mysql-replica
         - mysql-replica.svc

  mysql-configure-replication:
    image: mariadb:10.5
    environment:
      - "MYSQL_REPLICA_PASSWORD=toor"
      - "MYSQL_MAIN_PASSWORD=toor"
      - "MYSQL_ROOT_PASSWORD=toor"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./wbstack/docker-compose/wait-for-it.sh:/wait-for-it.sh:ro
      - ./wbstack/docker-compose/mysql/main:/mwdd-custom
      - mysql-configure-replication-data:/mwdd-connector
    command: /bin/bash -x /mwdd-custom/mysql_connector_main.sh

  mysql-replica-configure-replication:
    image: mariadb:10.5
    environment:
      - "MYSQL_REPLICA_PASSWORD=toor"
      - "MYSQL_MAIN_PASSWORD=toor"
      - "MYSQL_ROOT_PASSWORD=toor"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./wbstack/docker-compose/wait-for-it.sh:/wait-for-it.sh:ro
      - ./wbstack/docker-compose/mysql/replica:/mwdd-custom
      - mysql-configure-replication-data:/mwdd-connector
    command: /bin/bash -x /mwdd-custom/mysql_connector_replica.sh

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    networks:
      default:
        aliases:
          - redis.svc

  elasticsearch:
    image: wikibase/elasticsearch:6.5.4-wmde.1
    restart: unless-stopped
    ports:
      - 9200:9200
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  adminer:
    image: adminer:4.8.0
    ports:
      - 8003:8080

volumes:
  mediawiki-mysql-data:
  mysql-replica-data:
  mysql-configure-replication-data:
